name: my_assignment_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.13.1
  location: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.4
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
